# Generated by Django 3.1.4 on 2021-01-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_auto_20210117_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='textarea',
            field=models.TextField(max_length=250),
        ),
    ]
